name: kids_shapes_app
description: A kids learning app
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.6.3

flutter:
  uses-material-design: true